stages:
  - build
  - test

job_build:
  stage: build
  script:
    - echo "Building the project"
  tags:
    - docker

job_test:
  stage: test
  script:
    - echo "Running tests"
  tags:
    - docker
